#include <stdio.h>
int array[9][9],total=0;

void sd(int arr[][9],int a,int b)
{
    int bl,s,i,j,t=0;
    if(9==a)
    {
        s=0;
        for(i=0;i<9;i++)
        {
            for(j=0;j<9;j++)
            {
                if(i>4)
                    t=i-4;
                else
                    t=4-i;
                if(j>4)
                    bl=j-4;
                else
                    bl=4-j;
                if(t<bl)
                    t=bl;
                t=10-t;
                s+=arr[i][j]*t;
            }
            if(s>total)
            total=s; 
        }
    }else
    {
        if(arr[a][b]!=array[a][b])
        {
            for(t=1;t<=9;t++)
            {
                bl=1; 
                for(i=0;i<a;i++)
                {
                    if(t==arr[i][b])
                    {
                        bl=0;
                        break;
                    }
                }
                if(bl)
                {
                    for(i=a+1;i<9;i++)
                    {
                        if(t==array[i][b])
                        {
                            bl=0;
                            break;
                        }
                    }
                }
                if(bl)
                {
                    for(i=0;i<b;i++)
                    {
                        if(t==arr[a][i]) 
                        {
                            bl=0;
                            break;
                        }
                    }
                }
                if(bl)
                {
                    for(i=b+1;i<9;i++)
                    {
                        if(t==array[a][i])
                        {
                            bl=0;
                            break;
                        } 
                    }
                } 
                if(bl)
                {
                    for(i=a/3*3;i<a/3*3+3;i++)
                    {
                        for(j=b/3*3;j<b/3*3+3;j++)
                        {
                            if(i<a||(i==a&&j<b))
                            {
                                if(arr[i][j]==t)
                                {
                                    bl=0;
                                    break;
                                }
                            }
                            else if(t==array[i][j])
                            {
                                bl=0;
                                break;
                            }
                        }
                    }
                }
                if(bl)
                {
                    arr[a][b]=t;
                    if(b<8)
                        sd(arr,a,b+1);
                    else
                        sd(arr,a+1,0);  
                }
            }
        }
        else
        {
            if(b<8)
                sd(arr,a,b+1); 
            else
                sd(arr,a+1,0);
        }
    }
}
             
int main()
{
    FILE *fp1,*fp2;
    int arr[9][9],i,j;
    fp1=fopen("no2_in.txt","r");
    for(i=0;i<9;i++)
    {
        for(j=0;j<9;j++)
        {
            fscanf(fp1,"%d",&arr[i][j]);
            array[i][j]=arr[i][j];
            if(arr[i][j]==0)
                array[i][j]=10;
        }
    }
    fclose(fp1);
    sd(arr,0,0);
    fp2=fopen("no2_out.txt","w"); 
    fprintf(fp2,"%d",total); 
    printf("%d\n",total);
    fclose(fp2);
    getch();
    return 0;
}
